mosquitto:
  image: sbiermann/rpi-mosquitto
  container_name: "mosquitto"
  volumes:
    - /srv/mqtt/config:/mqtt/config:ro
    - /srv/mqtt/log:/mqtt/log
    - /srv/mqtt/data/:/mqtt/data
  ports:
    - "1883:1883"
    - "9001:9001"
  expose:
    - "1883"
    - "9001"

influxdb:
  image: pithings/rpi-influxdb
  container_name: "influxdb"
  volumes:
    - /var/lib/influxdb:/var/lib/influxdb
    - /var/log/influxdb:/var/log/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8083"
    - "8086"
  log_driver: "journald"

grafana:
  image: pithings/rpi-grafana
  container_name: "grafana"
  volumes:
    - /var/lib/grafana:/var/lib/grafana
    - /var/log/grafana:/var/log/grafana
  ports:
    - "3000:3000"
  log_driver: "journald"

home-assistant:
  image: pithings/rpi-homeassistant
  container_name: "home-assistant"
  devices:
    - /dev/ttyACM0:/dev/zwave
  volumes:
    - /var/local/homeassistant/config:/config
    - /etc/localtime:/etc/localtime:ro
    - /etc/apache2/ssl:/etc/apache2/ssl
  net: "host"
  log_driver: "journald"
